set MYSQL_HOST=127.0.0.1
set MYSQL_PORT=3307
set MYSQL_DATABASE=Project_Management
set MYSQL_USER=project_user
set MYSQL_PASSWORD=password
set MYSQL_DATASOURCE=ProjectManagementDS

echo MYSQL_HOST=%MYSQL_HOST%
echo MYSQL_PORT=%MYSQL_PORT%
echo MYSQL_DATABASE=%MYSQL_DATABASE%
echo MYSQL_USER=%MYSQL_USER%