USE Project_Management;

ALTER TABLE Employee
    MODIFY COLUMN system_role ENUM('ADMIN', 'HR', 'OPERATIONS_MANAGER', 'EMPLOYEE');

ALTER TABLE Timesheet
    ADD COLUMN status ENUM('DRAFT', 'SUBMITTED', 'APPROVED', 'RETURNED') NOT NULL DEFAULT 'DRAFT';

UPDATE Timesheet
SET status = CASE
    WHEN approved = b'1' THEN 'SUBMITTED'
    ELSE 'DRAFT'
END;

ALTER TABLE Timesheet
    DROP COLUMN approved;
